### ISSUE TITLE
Missing new line after issue prefix

### ISSUE THREAD

**Issue by ankh-bigpay** [avilaton/add-msg-issue-prefix-hook#19]
I use the following configuration

```yaml
- repo: https://github.com/avilaton/add-msg-issue-prefix-hook
  rev: v0.0.9
  hooks:
  - id: add-msg-issue-prefix
    args:
    - '--template={}:'
```

The commit message misses the new line after the issue prefix, pulling the Git comment to the first line

```
ABC-123: # Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
```

Version 0.0.6 works fine.

**Comment by artslob** [comment]
Hm, strange. When I run locally v0.0.6 (commit 59fb9d6) such command:
```bash
poetry run python add_msg_issue_prefix_hook/add_msg_issue_prefix.py '--template={}:' README.md
```
I get following diff:
```diff
-add-msg-issue-prefix-hook
+TASK-006: add-msg-issue-prefix-hook
```
Running same command on v0.0.7 (commit e3c2be8) gives following diff:
```diff
-add-msg-issue-prefix-hook
+ TASK-007: add-msg-issue-prefix-hook
```
So both versions don't add newline between prefix and original file content. But with following pre-commit config 
```yaml
❯ cat .pre-commit-config.yaml
repos:
-   repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.6  # Use the ref you want to point at
    hooks:
        - id: add-msg-issue-prefix
```
Changing version from `0.0.6` to `0.0.7` results in missing newline.

Biggest change is usage of `strip()` for strings https://github.com/avilaton/add-msg-issue-prefix-hook/compare/59fb9d6..e3c2be8.But locally 0.0.6 and 0.0.7 behave same :thinking: 

Could it be that when `add-msg-issue-prefix-hook` is being run by `pre-commit` original commit file has newline at the start of file? And `v0.0.7` calls `content.strip()` removing that newline?
