### ISSUE TITLE
Inconsistency between version in issue insertion

### ISSUE THREAD

**Issue by stickm4n** [avilaton/add-msg-issue-prefix-hook#24]
```yaml
  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.x
    hooks:
      - id: add-msg-issue-prefix
        args:
          - '--template=[{}]'
          - '--pattern=[a-zA-Z0-9]{1,10}-[0-9]{1,5}'
          - '--default=[NO-ISSUE]'
          - '--insert-after=^feat.?:|^fix.?:|^docs.?:|^style.?:|^refactor.?:|^test.?:|^chore.?:|^ci.?:|^build.?:|^perf.?:|^revert.?:'
```

`rev: v0.0.8` outputs -> `feat: [NO-ISSUE] commit message`
`rev: v0.0.11` outputs -> `feat:[NO-ISSUE]  commit message`

According to docs (and in my humble opinion) `v0.0.8` works fine but `v0.0.11` has one-char offset to the left of the insertion position.
